<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-Q0E3SEM" ignored="0" name="Test2" tests="1" failures="1" timestamp="20 Jun 2019 07:48:46 GMT" time="43.497" errors="0">
  <testcase name="ValidateAboutusTest" time="27.734" classname="com.v1.sm.testcases.ValidateAboutusTest">
    <failure type="java.lang.AssertionError" message="Failing the aboutus Test">
      <![CDATA[java.lang.AssertionError: Failing the aboutus Test
at com.v1.sm.testcases.ValidateAboutusTest.ValidateAboutusTest(ValidateAboutusTest.java:28)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- ValidateAboutusTest -->
</testsuite> <!-- Test2 -->
